#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProgettoInfo3.Resource", IsApplication=true)]

namespace ProgettoInfo3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BTLibrary.Resource.String.library_name = global::ProgettoInfo3.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Type = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060023
			public const int MyName = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int Sendname = 2131099684;
			
			// aapt resource value: 0x7f060009
			public const int Start = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int addr2 = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int addr3 = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int addr4 = 2131099673;
			
			// aapt resource value: 0x7f06001e
			public const int addr5 = 2131099678;
			
			// aapt resource value: 0x7f06000f
			public const int back = 2131099663;
			
			// aapt resource value: 0x7f060026
			public const int create = 2131099686;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout1 = 2131099679;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout10 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout11 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout12 = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout13 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout14 = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout15 = 2131099674;
			
			// aapt resource value: 0x7f060022
			public const int linearLayout2 = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout9 = 2131099648;
			
			// aapt resource value: 0x7f060021
			public const int newdev = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int paired = 2131099680;
			
			// aapt resource value: 0x7f060008
			public const int player1 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int player2 = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int player3 = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int player4 = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int player5 = 2131099677;
			
			// aapt resource value: 0x7f060025
			public const int scan = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int select = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int settings = 2131099688;
			
			// aapt resource value: 0x7f06000c
			public const int spinner1 = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int spinner2 = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int spinner3 = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int spinner4 = 2131099676;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int textView2 = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int textView3 = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int textView4 = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int textView5 = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int textView6 = 2131099675;
			
			// aapt resource value: 0x7f060003
			public const int textView7 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int textView8 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int textView9 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateTable = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_name = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeviceList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int Default1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Default2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Default3 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Default4 = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int change_name = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int create_title = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int none_add = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int scanning = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int select = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
