//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Engine
{
	public class Card
	{
		private Board _board;
		private EnSemi _seme;
		private EnNumbers _number;
		private Player _plIni;
		private Player _plFin;
		private int _gTurno;

		public EnSemi Seme { get { return _seme; } }

		public EnNumbers Number { get { return _number; } }

		public Player PlayerIniziale { get { return _plIni; } }

		public Player PlayerFinale { get { return _plFin; } }

		public int TurnoGiocata { get { return _gTurno; } }

		public bool isPlayable{ get { return _gTurno == -1; } }

		public Card (Board board, EnNumbers number, EnSemi seme, Player iniziale)
		{
			if (board.CurrentTurn != -1)
				throw new Exception ("Le carte si possono creare solo prima dell'inizio della partita");

			_board = board;
			_seme = seme;
			_number = number;
			_plIni = iniziale;

			_plIni = null;
			_gTurno = -1;
		}

		public void giocaCarta (int turno)
		{
			_gTurno = turno;
		}

		public void raccogliCarta (Player raccoglitore)
		{

			_plFin = raccoglitore;
		}

		public int getPunti ()
		{
			if (_number == EnNumbers.ASSE)
				return 11;
			else if (_number == EnNumbers.TRE)
				return 10;
			else if (_number == EnNumbers.RE)
				return 4;
			else if (_number == EnNumbers.CAVALLO)
				return 3;
			else if (_number == EnNumbers.FANTE)
				return 2;
			else if (_number == EnNumbers.SETTE && _seme == EnSemi.ORI)
				return 1;
			else
				return 0;
		}
	}
}

