//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Engine
{
	public class Player
	{
		private string _name;
		private EnRole _role;

		public string Name { get { return _name; } }

		public EnRole Role { get { return _role; } }

		public Player (string name, EnRole role)
		{
			_name = name;
			_role = role;
		}
	}
}

