//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Engine
{
	public class Player
	{
		/// <summary>
		/// The board used by this player.
		/// </summary>
		private Board _board;

		#region Name management

		/// <summary>
		/// The player's name.
		/// </summary>
		private string _name;

		/// <summary>
		/// Gets the player's name.
		/// </summary>
		/// <value>The name.</value>
		public string Name { get { return _name; } }

		#endregion

		#region Role management

		/// <summary>
		/// The player's role.
		/// </summary>
		private EnRole _role;

		/// <summary>
		/// Gets or sets the player's role, the role can't be change during the play time.
		/// </summary>
		/// <value>The role.</value>
		public EnRole Role {
			get { return _role; }
			set {
				if (_board.isPlayTime)
					throw new Exception ("The role can't be change during the play time");
				_role = value;
			}
		}

		#endregion

		/// <summary>
		/// Initializes a new instance of the <see cref="Engine.Player"/> class.
		/// </summary>
		/// <param name="board">The board used by this player.</param>
		/// <param name="name">The player's name.</param>
		public Player (Board board, string name)
		{
			if (!_board.isCreationTime)
				throw new Exception ("A player must be instantiated during the creation time");

			_board = board;
			_name = name;
		}
	}
}

