#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GUILayout.Resource", IsApplication=true)]

namespace GUILayout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BTLibrary.Resource.String.ApplicationName = global::GUILayout.Resource.String.ApplicationName;
			global::BTLibrary.Resource.String.Hello = global::GUILayout.Resource.String.Hello;
			global::BTLibrary.Resource.String.library_name = global::GUILayout.Resource.String.library_name;
			global::PCLStorage.Resource.String.ApplicationName = global::GUILayout.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::GUILayout.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Type = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int dark_red = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int green = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int light_red = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int assi = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int image_for_rotation = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int indeterminate = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int red_button = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080031
			public const int ButtonLatout = 2131230769;
			
			// aapt resource value: 0x7f08001c
			public const int Dealer1 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int Dealer2 = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int Dealer3 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int Dealer4 = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int Dealer5 = 2131230752;
			
			// aapt resource value: 0x7f08001b
			public const int DealerGroup = 2131230747;
			
			// aapt resource value: 0x7f08002d
			public const int Delete = 2131230765;
			
			// aapt resource value: 0x7f080028
			public const int Disconnect = 2131230760;
			
			// aapt resource value: 0x7f080030
			public const int ImageLayout = 2131230768;
			
			// aapt resource value: 0x7f080022
			public const int Layout = 2131230754;
			
			// aapt resource value: 0x7f080026
			public const int MyName = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int Sendname = 2131230759;
			
			// aapt resource value: 0x7f080019
			public const int Start = 2131230745;
			
			// aapt resource value: 0x7f08002e
			public const int TitleLayout = 2131230766;
			
			// aapt resource value: 0x7f080014
			public const int addr2 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int addr3 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int addr4 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int addr5 = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int back = 2131230746;
			
			// aapt resource value: 0x7f08002c
			public const int backHistory = 2131230764;
			
			// aapt resource value: 0x7f080032
			public const int create = 2131230770;
			
			// aapt resource value: 0x7f08002a
			public const int gridView1 = 2131230762;
			
			// aapt resource value: 0x7f080034
			public const int history = 2131230772;
			
			// aapt resource value: 0x7f080029
			public const int linearLayout1 = 2131230761;
			
			// aapt resource value: 0x7f08002b
			public const int linearLayout2 = 2131230763;
			
			// aapt resource value: 0x7f080024
			public const int newdev = 2131230756;
			
			// aapt resource value: 0x7f080021
			public const int paired = 2131230753;
			
			// aapt resource value: 0x7f08000e
			public const int player1 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int player2 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int player3 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int player4 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int player5 = 2131230738;
			
			// aapt resource value: 0x7f080025
			public const int progress = 2131230757;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f08002f
			public const int relativeLayout3 = 2131230767;
			
			// aapt resource value: 0x7f080023
			public const int scan = 2131230755;
			
			// aapt resource value: 0x7f080033
			public const int select = 2131230771;
			
			// aapt resource value: 0x7f080009
			public const int spinner1 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int spinner2 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int spinner3 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int spinner4 = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f080013
			public const int textView11 = 2131230739;
			
			// aapt resource value: 0x7f080018
			public const int textView12 = 2131230744;
			
			// aapt resource value: 0x7f080002
			public const int textView2 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int textView3 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int textView4 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int textView5 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int textView6 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int textView7 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int textView8 = 2131230728;
			
			// aapt resource value: 0x7f08000d
			public const int textView9 = 2131230733;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateTable = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_name = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeviceList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Grid = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Grid_elem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int History = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Default1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Default2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Default3 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Default4 = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int change_name = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int connecting = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int create_title = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int none_add = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int scanning = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int select = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int starting = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int Grid = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int Text = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int button_text = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int create_btn = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int create_txt = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
