//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Engine
{
	public enum EnSemi	//Enumerativo dei semi
	{
		ORI,
		COPE,
		BASTONI,
		SPADE,
	}

	public enum EnNumbers	//Enumerativo dei numeri
	{
		ASSE,
		DUE,
		TRE,
		QUATTRO,
		CINQUE,
		SEI,
		SETTE,
		FANTE,
		CAVALLO,
		RE,
	}
}

